plugins {
    id 'groovy'
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'com.gradle.plugin-publish' version '1.2.1'
}

group = 'com.ajsoftware.scaffold'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
}

// Evitar duplicados en processResources
processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

gradlePlugin {
    plugins {
        scaffoldMain {
            id = 'com.ajsoftware.scaffold'
            implementationClass = 'com.ajsoftware.scaffold.ScaffoldingPlugin'
        }
        scaffoldProject {
            id = 'com.ajsoftware.scaffold.project'
            implementationClass = 'com.ajsoftware.scaffold.project.ProjectPlugin'
        }
        scaffoldModule {
            id = 'com.ajsoftware.scaffold.module'
            implementationClass = 'com.ajsoftware.scaffold.module.ModulePlugin'
        }
        scaffoldDelete {
            id = 'com.ajsoftware.scaffold.delete'
            implementationClass = 'com.ajsoftware.scaffold.delete.DeletePlugin'
        }
        scaffoldComponent {
            id = 'com.ajsoftware.scaffold.component'
            implementationClass = 'com.ajsoftware.scaffold.component.ComponentPlugin'
        }
    }
}

apply from: 'publish.gradle'

// Configuración para Gradle Plugin Portal
gradlePlugin {
    website = 'https://github.com/SteverWiw/scaffolding'
    vcsUrl = 'https://github.com/SteverWiw/scaffolding.git'
}